services:
  # Use root/r00tpa55 as user/password credentials
  dbs:
    image: mariadb
    # container_name: database
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: r00tpa55
    networks:
      - jsp-net
    volumes:
      - jsp-bookstore-data:/var/lib/mysql

  tomcat:
    # container_name: tomcat
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8480:8080"
    networks:
      - jsp-net
    
  adminer:
    image: adminer:latest
    restart: unless-stopped
    # container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: dbs
      ADMINER_DESIGN: "lucas-sandery" # https://github.com/vrana/adminer/tree/master/designs
    ports:
      - "8491:8080"
    networks:
      - jsp-net

#  alpine:
#     # container_name: alpine
#     build:
#       context: ./alpine
#       dockerfile: ./Dockerfile
#     networks:
#       - jsp-net
#     volumes:
#      - .\alpine\repo:/home/devel/repo

networks:
  jsp-net:
    driver: bridge

volumes:
  jsp-bookstore-data:
    external: true